SET(GRF_PROJECT grf)
SET(GRF_HOME ${ROKLEGEND_DEPENDENCIES_DIR}/grf)

ADD_SUBDIRECTORY(${GRF_HOME})
ADD_DEPENDENCIES(${GRF_PROJECT} ${ZLIB_LIBRARY_NAME})

RO_TARGET_ENABLE_AVX2(${GRF_PROJECT})

SET(GRF_INCLUDE_DIRS ${GRF_HOME}/includes)
SET(GRF_LIBRARIES debug ${ROKLEGEND_LIB_DIR}/Debug/grf_d.lib optimized ${ROKLEGEND_LIB_DIR}/Release/grf.lib)