# Macro to link target libraries given a RokLegend module.
MACRO(RO_TARGET_LINK_LIBRARIES TARGET)
    SET(MODULE_LIBS "")
    FOREACH(LIB_NAME ${ARGN})
        TARGET_LINK_LIBRARIES(
            ${TARGET}
            debug ${ROKLEGEND_LIB_DIR_DBG}/${LIB_NAME}_d.lib
            optimized ${ROKLEGEND_LIB_DIR_REL}/${LIB_NAME}.lib
        )
    ENDFOREACH()
ENDMACRO()

# Macro to set source-group for a list of files
MACRO(RO_SOURCE_GROUP GROUP_NAME)
    SET(HEADER_FILES "")
    SET(SOURCE_FILES "")
	SET(OTHER_FILES "")
	SET(HEADER_EXTENSIONS ".h" ".hpp" ".hxx")
	SET(SOURCE_EXTENSIONS ".cpp" ".c" ".cxx")
    FOREACH(CXX_FILE ${ARGN})
        GET_FILENAME_COMPONENT(CXX_EXT ${CXX_FILE} EXT)
		IF (NOT "${CXX_EXT}" STREQUAL "")
			LIST(FIND HEADER_EXTENSIONS ${CXX_EXT} IS_HEADER)
			IF (${IS_HEADER})
				LIST(APPEND HEADER_FILES ${CXX_FILE})
			ELSE ()
				LIST(FIND SOURCE_EXTENSIONS ${CXX_EXT} IS_SOURCE)
				IF (${IS_SOURCE})
					LIST(APPEND SOURCE_FILES ${CXX_FILE})
				ELSE ()
					LIST(APPEND OTHER_FILES ${CXX_FILE})
				ENDIF ()
			ENDIF ()
		ENDIF ()
    ENDFOREACH()
    SOURCE_GROUP(${ROKLEGEND_HXX_SOURCE_GROUP}\\${GROUP_NAME} FILES ${HEADER_FILES})
    SOURCE_GROUP(${ROKLEGEND_CXX_SOURCE_GROUP}\\${GROUP_NAME} FILES ${SOURCE_FILES})
	SOURCE_GROUP(${GROUP_NAME} FILES ${OTHER_FILES})
ENDMACRO()